### PR TITLE
Listpagestyling lp

### PR DESCRIPTION
**Pull request by lapinell**

### CODE REVIEW

**Review by salegre — CHANGES_REQUESTED** [review]
## Review

- [x]  "Images Coming Soon" Image displaying improperly big on inventory
- [x]   Related products on VDP page should be on a grid

**Comment by lapinell** [comment]
## Requested Changes

- For the related products - PM said list format was fine -- so I put a max-width of 1090 on them to make them look "nicer"
- For Images Coming Soon, I put a min and max width on them

**Comment by salegre** [comment]
## Review 1

You're only putting the max width on placeholder images. 
- [x] Try using the class applied to all listings, et_shop_image and specify a max width of 275px (suggestion)

Made new card in backlog for gridview

**Review by salegre — APPROVED** [review]
Looking good!

**Pull request merged**
